const actionTypes = {
  SET_GROUPS: 'SET_GROUPS',
  SET_GROUP: 'SET_GROUP',
  ADD_GROUP: 'ADD_GROUP',
  DEL_GROUP: 'DEL_GROUP',

  SET_STUDENTS: 'SET_STUDENTS',
  SET_STUDENT: 'SET_STUDENT',
  DEL_STUDENT: 'DEL_STUDENT',

  SET_AUTH_LOADING: 'SET_AUTH_LOADING',
  SET_CAMP_LOADING: 'SET_CAMP_LOADING',
  SET_STUD_LOADING: 'SET_STUD_LOADING:',

  ERROR: 'ERROR',

  SET_AUTH: 'SET_AUTH',
  SET_USER: 'SET_USER'
};

export default actionTypes
